add test and correct .yml

diff --git a/.github/workflows/github-workflow.yml b/.github/workflows/github-workflow.yml
--- a/.github/workflows/github-workflow.yml
+++ b/.github/workflows/github-workflow.yml
@@ -7,13 +7,31 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Use Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20.x'
-      - name:  build docusaurus
-        run: npm run build
+    - name: Checkout repository
+      uses: actions/checkout@v3
+
+    - name: Set up Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '16'
+
+    - name: Install dependencies
+      working-directory: my_site
+      run: npm install
+
+    - name: Build Docusaurus site
+      working-directory: my_site
+      run: npm run build
+
+    - name: Run build tests
+      working-directory: my_site
+      run: |
+        if [ ! -d "./build" ]; then
+          echo "Build directory not found!"
+          exit 1
+        fi
+        echo "Build directory found."
+
       - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
